export default {
  reviewOne: {
    companyName: '名称',
    socialCode: '统一社会信用代码',
    residence: '住所',
    contactNumber: '联系电话',
    postalCode: '邮政编码',
    nameOfLegalRepresentative: '法定代表人姓名',
    typeOfCompany: '公司类型',
    registeredCapital: '注册资本',
    totalInvestment: '投资总额',
    modeOfEstablishment: '设立方式',
    applyForALicense: '申领执照',
    businessScope: '经营范围',
    businessTerm: '营业期限/经营期限'
  },
  reviewTwo: {
    name: '身份证：姓名',
    sex: '身份证：性别',
    address: '身份证：地址',
    birthDate: '身份证：生日',
    idNumber: '身份证：证件号码',
    issueAuthority: '身份证：签发机关',
    validPeriod: '身份证：有效日期',
    landlineTelephone: '固定电话',
    mobilePhone: '移动电话',
    signatureDate: '签署日期',
    signatureOfDesignated: '指定代表/委托代理人签字',
    signatureOfLegalRepresentative: '法定代表人签字'
  },
  reviewThree: {
    name: '身份证：姓名',
    formName: '姓名',
    address: '地址',
    birthDate: '身份证：生日',
    country: '国家',
    productionMode: '产生方式',
    typeOfldentityDocument: '身份证件类型',
    idNumber: '身份证：身份证件号码',
    validPeriod: '身份证：有效期限',
    typeOfIdentityDocument: '身份证类型',
    formIdNumber: '身份证件号码',
    landlineTelephone: '固定电话',
    mobilePhone: '移动电话',
    residence: '住所',
    emailAddress: '电子邮箱',
    signatureOfTheProposedLegalRepresentative: '拟任法定代表人签字',
    signatureDate: '签字日期'
  },
  reviewFour: {
    address: '身份证住址',
    birthDate: '身份证：生日',
    emailAddress: '电子邮箱',
    formIdNumber: '身份证件号码',
    formName: '姓名',
    idNumber: '身份证：身份证号码',
    issueAuthority: '产生方式',
    landlineTelephone: '固定电话',
    mobilePhone: '移动电话',
    name: '身份证：姓名',
    sex: '身份证：性别',
    typeOfIdentityDocument: '身份证件类型',
    validPeriod: '身份证：有效期限'
  },
  reviewFive: {
    name: '姓名',
    country: '国别(地区)',
    job: '职务',
    productionMode: '产生方式',
    typeOfIdentityDocument: '身份证件类型',
    idNumber: '身份证件号码',
    mobilePhone: '移动电话'
  },
  reviewSix: {
    stockholder: '股东(发起人)、外国投资者名称或姓名',
    country: '国别(地区)',
    documentType: '证件类型',
    documentNumber: '证件号码',
    subscriptionAmountOfCapitalContribution: '认缴出资额',
    paidInCapitalContribution: '实缴出资额',
    timeOfInvestment: '出资(认缴)时间',
    wayOfInvestment: '出资方式'
  },
  reviewSeven: {
    name: '姓名',
    mobilePhone: '移动电话',
    typeOfIdentityDocument: '身份证件类型',
    landlineTelephone: '固定电话',
    emailAddress: '电子邮箱',
    idNumber: '身份证件号码'
  }
}
